### ISSUE TITLE
[BUG] Error when switching platforms and updating SDK on all my projects

### ISSUE THREAD

**Issue by Rycia** [VRLabs/Marker#32]
![image](https://github.com/user-attachments/assets/d2190321-f7bc-4a83-862b-7d8b72e3a2b1)
If I remove the package, remove the marker, and reinstall it, it works as intended.
This is across 10+ projects, and my solution has been to reinstall it, but this is annoying when you have tens of projects.
This prevents upload and shows the "safe mode" dialog box unless it's reinstalled completely.

```Packages\dev.vrlabs.marker\Editor\MarkerEditor.cs(30,20): error CS0246: The type or namespace name 'ScriptFunctions' could not be found (are you missing a using directive or an assembly reference?)```

**Comment by Rycia** [comment]
Then.. when switching platform to iOS and then removing the marker:
![{47FDF9CC-11BF-4EAD-BAD6-8EB4009FD431}](https://github.com/user-attachments/assets/18cbc48c-0e30-4d17-b2e3-ff534812d9fc)

**Comment by Rycia** [comment]
Repo seems pretty abandoned if an issue like this has gone ignored.

**Comment by jellejurre** [comment]
To give some insight into this: you said the issue has a solution, and the team is working on a  2.0 release for the marker which will address open issues, therefore solving issues on the 1.0 marker is not something that is seen as very high priority.
